development: &default
  adapter: postgresql
  encoding: unicode
  database: watchlist_development
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>

test:
  <<: *default
  database: watchlist_test

production:
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  url:  <%= ENV.fetch("DATABASE_URL") if Rails.env.production? %>
